export { Navbar } from "./Navbar";
export { HeroSection } from "./HeroSection";
export { StatsBar } from "./StatsBar";
export { ServicesSection } from "./ServicesSection";
export { HowItWorksSection } from "./HowItWorksSection";
export { PricingBand } from "./PricingBand";
export { ArtisanSection } from "./ArtisanSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { FaqSection } from "./FaqSection";
export { CoverageSection } from "./CoverageSection";
export { CtaSection } from "./CtaSection";
export { Footer } from "./Footer";
export { PhoneMockup } from "./PhoneMockup";
export { AppDownloadBanner } from "./AppDownloadBanner";
export { FloatingWhatsApp } from "./FloatingWhatsApp";
export { MobileStickyCta } from "./MobileStickyCta";
export { AppStoreBadge, GooglePlayBadge, StoreBadgePair as StoreBadges } from "@/components/ui/store-badges";
export { TrustBadges } from "./TrustBadges";
